apiVersion: apps/v1
kind: Deployment
metadata:
    name: edureka-deployment
spec:
  replicas: 2
  minReadySeconds: 45
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
  selector:
   matchLabels:
           app: edureka
  template:
    metadata:
        name: edureka-pod
        labels:
           app: edureka
    spec:
      containers:
       - name: edureka-cont
         image: nutan69/edurekaproject
         ports:
           - containerPort: 8080
      imagePullSecrets:
        - name: regcred
      tolerations:
       - key: node-role.kubernetes.io/master
         operator: Exists
         effect: NoSchedule

---          
apiVersion: v1
kind: Service
metadata:
    name: edureka-service
spec:
   type: NodePort
   selector:
        app: edureka
   ports:
     - port: 80   #cluster port
       targetPort: 8080 # container image port
