---
- hosts: localhost
  become: yes
  name: play1
  tasks:
    - name: creating a image and run it as a container
      docker_image:
              path: /var/lib/jenkins/workspace/EdurekaProject
              name: nutan69/edurekaproject
              tag: v1
      
