---
- hosts: localhost
  become: yes
  name: play1
  tasks:
    - name: creating a image and push to docker hub
      docker_image:
             build:
                path: /var/lib/jenkins/workspace/EdurekaProject
             name: nutan69/edurekaproject
             source: build
             push: true
      tags: v1
    - name: create a secret for private repository images
      command: kubectl create -f secret.yml
      tags: v2
    - name: creating a deployment and service
      command: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f deploy.yml
      tags: v3
