---
- hosts: localhost
  become: yes
  name: play1
  tasks:
    - name: creating a image and run it as a container
      command: sudo docker build -f Dockerfile -t nutan69/edurekaproject .
      command: sudo docker login -u nutan69 -p nutanni@69
      command: sudo docker push nutan69/edurekaproject
      
